// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: KVStore.proto

#include "KVStore.pb.h"
#include "KVStore.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace KVStore {

static const char* KVStore_method_names[] = {
  "/KVStore.KVStore/Get",
  "/KVStore.KVStore/Set",
};

std::unique_ptr< KVStore::Stub> KVStore::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KVStore::Stub> stub(new KVStore::Stub(channel, options));
  return stub;
}

KVStore::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Get_(KVStore_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Set_(KVStore_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KVStore::Stub::Get(::grpc::ClientContext* context, const ::KVStore::GetRequest& request, ::KVStore::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::KVStore::GetRequest, ::KVStore::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Get_, context, request, response);
}

void KVStore::Stub::async::Get(::grpc::ClientContext* context, const ::KVStore::GetRequest* request, ::KVStore::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::KVStore::GetRequest, ::KVStore::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KVStore::Stub::async::Get(::grpc::ClientContext* context, const ::KVStore::GetRequest* request, ::KVStore::GetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::KVStore::GetResponse>* KVStore::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::KVStore::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::KVStore::GetResponse, ::KVStore::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader< ::KVStore::GetResponse>* KVStore::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::KVStore::GetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status KVStore::Stub::Set(::grpc::ClientContext* context, const ::KVStore::SetRequest& request, ::KVStore::SetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::KVStore::SetRequest, ::KVStore::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Set_, context, request, response);
}

void KVStore::Stub::async::Set(::grpc::ClientContext* context, const ::KVStore::SetRequest* request, ::KVStore::SetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::KVStore::SetRequest, ::KVStore::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void KVStore::Stub::async::Set(::grpc::ClientContext* context, const ::KVStore::SetRequest* request, ::KVStore::SetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::KVStore::SetResponse>* KVStore::Stub::PrepareAsyncSetRaw(::grpc::ClientContext* context, const ::KVStore::SetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::KVStore::SetResponse, ::KVStore::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader< ::KVStore::SetResponse>* KVStore::Stub::AsyncSetRaw(::grpc::ClientContext* context, const ::KVStore::SetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

KVStore::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVStore_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVStore::Service, ::KVStore::GetRequest, ::KVStore::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVStore::Service* service,
             ::grpc::ServerContext* ctx,
             const ::KVStore::GetRequest* req,
             ::KVStore::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KVStore_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KVStore::Service, ::KVStore::SetRequest, ::KVStore::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](KVStore::Service* service,
             ::grpc::ServerContext* ctx,
             const ::KVStore::SetRequest* req,
             ::KVStore::SetResponse* resp) {
               return service->Set(ctx, req, resp);
             }, this)));
}

KVStore::Service::~Service() {
}

::grpc::Status KVStore::Service::Get(::grpc::ServerContext* context, const ::KVStore::GetRequest* request, ::KVStore::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVStore::Service::Set(::grpc::ServerContext* context, const ::KVStore::SetRequest* request, ::KVStore::SetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace KVStore

