// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MapReduce.proto
#ifndef GRPC_MapReduce_2eproto__INCLUDED
#define GRPC_MapReduce_2eproto__INCLUDED

#include "MapReduce.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace MapReduce {

class TaskService final {
 public:
  static constexpr char const* service_full_name() {
    return "MapReduce.TaskService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::MapReduce::AckAndQueryNewTaskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MapReduce::AckAndQueryNewTaskResponse>> AsyncAckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MapReduce::AckAndQueryNewTaskResponse>>(AsyncAckAndQueryNewTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MapReduce::AckAndQueryNewTaskResponse>> PrepareAsyncAckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MapReduce::AckAndQueryNewTaskResponse>>(PrepareAsyncAckAndQueryNewTaskRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MapReduce::AckAndQueryNewTaskResponse>* AsyncAckAndQueryNewTaskRaw(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MapReduce::AckAndQueryNewTaskResponse>* PrepareAsyncAckAndQueryNewTaskRaw(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::MapReduce::AckAndQueryNewTaskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>> AsyncAckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>>(AsyncAckAndQueryNewTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>> PrepareAsyncAckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>>(PrepareAsyncAckAndQueryNewTaskRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response, std::function<void(::grpc::Status)>) override;
      void AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>* AsyncAckAndQueryNewTaskRaw(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>* PrepareAsyncAckAndQueryNewTaskRaw(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AckAndQueryNewTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AckAndQueryNewTask(::grpc::ServerContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AckAndQueryNewTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AckAndQueryNewTask() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AckAndQueryNewTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AckAndQueryNewTask(::grpc::ServerContext* /*context*/, const ::MapReduce::AckAndQueryNewTaskRequest* /*request*/, ::MapReduce::AckAndQueryNewTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAckAndQueryNewTask(::grpc::ServerContext* context, ::MapReduce::AckAndQueryNewTaskRequest* request, ::grpc::ServerAsyncResponseWriter< ::MapReduce::AckAndQueryNewTaskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AckAndQueryNewTask<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AckAndQueryNewTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AckAndQueryNewTask() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response) { return this->AckAndQueryNewTask(context, request, response); }));}
    void SetMessageAllocatorFor_AckAndQueryNewTask(
        ::grpc::MessageAllocator< ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AckAndQueryNewTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AckAndQueryNewTask(::grpc::ServerContext* /*context*/, const ::MapReduce::AckAndQueryNewTaskRequest* /*request*/, ::MapReduce::AckAndQueryNewTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AckAndQueryNewTask(
      ::grpc::CallbackServerContext* /*context*/, const ::MapReduce::AckAndQueryNewTaskRequest* /*request*/, ::MapReduce::AckAndQueryNewTaskResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AckAndQueryNewTask<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AckAndQueryNewTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AckAndQueryNewTask() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AckAndQueryNewTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AckAndQueryNewTask(::grpc::ServerContext* /*context*/, const ::MapReduce::AckAndQueryNewTaskRequest* /*request*/, ::MapReduce::AckAndQueryNewTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AckAndQueryNewTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AckAndQueryNewTask() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AckAndQueryNewTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AckAndQueryNewTask(::grpc::ServerContext* /*context*/, const ::MapReduce::AckAndQueryNewTaskRequest* /*request*/, ::MapReduce::AckAndQueryNewTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAckAndQueryNewTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AckAndQueryNewTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AckAndQueryNewTask() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AckAndQueryNewTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_AckAndQueryNewTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AckAndQueryNewTask(::grpc::ServerContext* /*context*/, const ::MapReduce::AckAndQueryNewTaskRequest* /*request*/, ::MapReduce::AckAndQueryNewTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AckAndQueryNewTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AckAndQueryNewTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AckAndQueryNewTask() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse>* streamer) {
                       return this->StreamedAckAndQueryNewTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AckAndQueryNewTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AckAndQueryNewTask(::grpc::ServerContext* /*context*/, const ::MapReduce::AckAndQueryNewTaskRequest* /*request*/, ::MapReduce::AckAndQueryNewTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAckAndQueryNewTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MapReduce::AckAndQueryNewTaskRequest,::MapReduce::AckAndQueryNewTaskResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AckAndQueryNewTask<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AckAndQueryNewTask<Service > StreamedService;
};

}  // namespace MapReduce


#endif  // GRPC_MapReduce_2eproto__INCLUDED
