// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MapReduce.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_MapReduce_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_MapReduce_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MapReduce_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MapReduce_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_MapReduce_2eproto;
namespace MapReduce {
class AckAndQueryNewTaskRequest;
struct AckAndQueryNewTaskRequestDefaultTypeInternal;
extern AckAndQueryNewTaskRequestDefaultTypeInternal _AckAndQueryNewTaskRequest_default_instance_;
class AckAndQueryNewTaskResponse;
struct AckAndQueryNewTaskResponseDefaultTypeInternal;
extern AckAndQueryNewTaskResponseDefaultTypeInternal _AckAndQueryNewTaskResponse_default_instance_;
class Task;
struct TaskDefaultTypeInternal;
extern TaskDefaultTypeInternal _Task_default_instance_;
}  // namespace MapReduce
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace MapReduce {

// ===================================================================


// -------------------------------------------------------------------

class Task final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MapReduce.Task) */ {
 public:
  inline Task() : Task(nullptr) {}
  ~Task() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Task(::google::protobuf::internal::ConstantInitialized);

  inline Task(const Task& from)
      : Task(nullptr, from) {}
  Task(Task&& from) noexcept
    : Task() {
    *this = ::std::move(from);
  }

  inline Task& operator=(const Task& from) {
    CopyFrom(from);
    return *this;
  }
  inline Task& operator=(Task&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Task& default_instance() {
    return *internal_default_instance();
  }
  static inline const Task* internal_default_instance() {
    return reinterpret_cast<const Task*>(
               &_Task_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Task& a, Task& b) {
    a.Swap(&b);
  }
  inline void Swap(Task* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Task* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Task* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Task>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Task& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Task& from) {
    Task::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Task* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "MapReduce.Task";
  }
  protected:
  explicit Task(::google::protobuf::Arena* arena);
  Task(::google::protobuf::Arena* arena, const Task& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kStateFieldNumber = 2,
    kFileFieldNumber = 4,
    kWorkerIdFieldNumber = 5,
    kIndexFieldNumber = 3,
  };
  // string id = 1;
  void clear_id() ;
  const std::string& id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* value);

  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(
      const std::string& value);
  std::string* _internal_mutable_id();

  public:
  // string state = 2;
  void clear_state() ;
  const std::string& state() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_state(Arg_&& arg, Args_... args);
  std::string* mutable_state();
  PROTOBUF_NODISCARD std::string* release_state();
  void set_allocated_state(std::string* value);

  private:
  const std::string& _internal_state() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_state(
      const std::string& value);
  std::string* _internal_mutable_state();

  public:
  // string file = 4;
  void clear_file() ;
  const std::string& file() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_file(Arg_&& arg, Args_... args);
  std::string* mutable_file();
  PROTOBUF_NODISCARD std::string* release_file();
  void set_allocated_file(std::string* value);

  private:
  const std::string& _internal_file() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file(
      const std::string& value);
  std::string* _internal_mutable_file();

  public:
  // string workerId = 5;
  void clear_workerid() ;
  const std::string& workerid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_workerid(Arg_&& arg, Args_... args);
  std::string* mutable_workerid();
  PROTOBUF_NODISCARD std::string* release_workerid();
  void set_allocated_workerid(std::string* value);

  private:
  const std::string& _internal_workerid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_workerid(
      const std::string& value);
  std::string* _internal_mutable_workerid();

  public:
  // int32 index = 3;
  void clear_index() ;
  ::int32_t index() const;
  void set_index(::int32_t value);

  private:
  ::int32_t _internal_index() const;
  void _internal_set_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:MapReduce.Task)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      42, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr state_;
    ::google::protobuf::internal::ArenaStringPtr file_;
    ::google::protobuf::internal::ArenaStringPtr workerid_;
    ::int32_t index_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MapReduce_2eproto;
};// -------------------------------------------------------------------

class AckAndQueryNewTaskRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MapReduce.AckAndQueryNewTaskRequest) */ {
 public:
  inline AckAndQueryNewTaskRequest() : AckAndQueryNewTaskRequest(nullptr) {}
  ~AckAndQueryNewTaskRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AckAndQueryNewTaskRequest(::google::protobuf::internal::ConstantInitialized);

  inline AckAndQueryNewTaskRequest(const AckAndQueryNewTaskRequest& from)
      : AckAndQueryNewTaskRequest(nullptr, from) {}
  AckAndQueryNewTaskRequest(AckAndQueryNewTaskRequest&& from) noexcept
    : AckAndQueryNewTaskRequest() {
    *this = ::std::move(from);
  }

  inline AckAndQueryNewTaskRequest& operator=(const AckAndQueryNewTaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AckAndQueryNewTaskRequest& operator=(AckAndQueryNewTaskRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AckAndQueryNewTaskRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AckAndQueryNewTaskRequest* internal_default_instance() {
    return reinterpret_cast<const AckAndQueryNewTaskRequest*>(
               &_AckAndQueryNewTaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AckAndQueryNewTaskRequest& a, AckAndQueryNewTaskRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AckAndQueryNewTaskRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AckAndQueryNewTaskRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AckAndQueryNewTaskRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AckAndQueryNewTaskRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AckAndQueryNewTaskRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AckAndQueryNewTaskRequest& from) {
    AckAndQueryNewTaskRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AckAndQueryNewTaskRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "MapReduce.AckAndQueryNewTaskRequest";
  }
  protected:
  explicit AckAndQueryNewTaskRequest(::google::protobuf::Arena* arena);
  AckAndQueryNewTaskRequest(::google::protobuf::Arena* arena, const AckAndQueryNewTaskRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 2,
    kWorkerIdFieldNumber = 3,
    kPreviousTaskIndexFieldNumber = 1,
  };
  // string state = 2;
  void clear_state() ;
  const std::string& state() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_state(Arg_&& arg, Args_... args);
  std::string* mutable_state();
  PROTOBUF_NODISCARD std::string* release_state();
  void set_allocated_state(std::string* value);

  private:
  const std::string& _internal_state() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_state(
      const std::string& value);
  std::string* _internal_mutable_state();

  public:
  // string workerId = 3;
  void clear_workerid() ;
  const std::string& workerid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_workerid(Arg_&& arg, Args_... args);
  std::string* mutable_workerid();
  PROTOBUF_NODISCARD std::string* release_workerid();
  void set_allocated_workerid(std::string* value);

  private:
  const std::string& _internal_workerid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_workerid(
      const std::string& value);
  std::string* _internal_mutable_workerid();

  public:
  // int32 previousTaskIndex = 1;
  void clear_previoustaskindex() ;
  ::int32_t previoustaskindex() const;
  void set_previoustaskindex(::int32_t value);

  private:
  ::int32_t _internal_previoustaskindex() const;
  void _internal_set_previoustaskindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:MapReduce.AckAndQueryNewTaskRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      57, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr state_;
    ::google::protobuf::internal::ArenaStringPtr workerid_;
    ::int32_t previoustaskindex_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MapReduce_2eproto;
};// -------------------------------------------------------------------

class AckAndQueryNewTaskResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MapReduce.AckAndQueryNewTaskResponse) */ {
 public:
  inline AckAndQueryNewTaskResponse() : AckAndQueryNewTaskResponse(nullptr) {}
  ~AckAndQueryNewTaskResponse() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AckAndQueryNewTaskResponse(::google::protobuf::internal::ConstantInitialized);

  inline AckAndQueryNewTaskResponse(const AckAndQueryNewTaskResponse& from)
      : AckAndQueryNewTaskResponse(nullptr, from) {}
  AckAndQueryNewTaskResponse(AckAndQueryNewTaskResponse&& from) noexcept
    : AckAndQueryNewTaskResponse() {
    *this = ::std::move(from);
  }

  inline AckAndQueryNewTaskResponse& operator=(const AckAndQueryNewTaskResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AckAndQueryNewTaskResponse& operator=(AckAndQueryNewTaskResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AckAndQueryNewTaskResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AckAndQueryNewTaskResponse* internal_default_instance() {
    return reinterpret_cast<const AckAndQueryNewTaskResponse*>(
               &_AckAndQueryNewTaskResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AckAndQueryNewTaskResponse& a, AckAndQueryNewTaskResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AckAndQueryNewTaskResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AckAndQueryNewTaskResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AckAndQueryNewTaskResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AckAndQueryNewTaskResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AckAndQueryNewTaskResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AckAndQueryNewTaskResponse& from) {
    AckAndQueryNewTaskResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AckAndQueryNewTaskResponse* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "MapReduce.AckAndQueryNewTaskResponse";
  }
  protected:
  explicit AckAndQueryNewTaskResponse(::google::protobuf::Arena* arena);
  AckAndQueryNewTaskResponse(::google::protobuf::Arena* arena, const AckAndQueryNewTaskResponse& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTaskFieldNumber = 1,
    kMapWorkerCntFieldNumber = 2,
    kReduceWorkerCntFieldNumber = 3,
  };
  // .MapReduce.Task task = 1;
  bool has_task() const;
  void clear_task() ;
  const ::MapReduce::Task& task() const;
  PROTOBUF_NODISCARD ::MapReduce::Task* release_task();
  ::MapReduce::Task* mutable_task();
  void set_allocated_task(::MapReduce::Task* value);
  void unsafe_arena_set_allocated_task(::MapReduce::Task* value);
  ::MapReduce::Task* unsafe_arena_release_task();

  private:
  const ::MapReduce::Task& _internal_task() const;
  ::MapReduce::Task* _internal_mutable_task();

  public:
  // int32 mapWorkerCnt = 2;
  void clear_mapworkercnt() ;
  ::int32_t mapworkercnt() const;
  void set_mapworkercnt(::int32_t value);

  private:
  ::int32_t _internal_mapworkercnt() const;
  void _internal_set_mapworkercnt(::int32_t value);

  public:
  // int32 reduceWorkerCnt = 3;
  void clear_reduceworkercnt() ;
  ::int32_t reduceworkercnt() const;
  void set_reduceworkercnt(::int32_t value);

  private:
  ::int32_t _internal_reduceworkercnt() const;
  void _internal_set_reduceworkercnt(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:MapReduce.AckAndQueryNewTaskResponse)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::MapReduce::Task* task_;
    ::int32_t mapworkercnt_;
    ::int32_t reduceworkercnt_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MapReduce_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Task

// string id = 1;
inline void Task::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_.ClearToEmpty();
}
inline const std::string& Task::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MapReduce.Task.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task::set_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MapReduce.Task.id)
}
inline std::string* Task::mutable_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:MapReduce.Task.id)
  return _s;
}
inline const std::string& Task::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_.Get();
}
inline void Task::_internal_set_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_.Set(value, GetArena());
}
inline std::string* Task::_internal_mutable_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.id_.Mutable( GetArena());
}
inline std::string* Task::release_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:MapReduce.Task.id)
  return _impl_.id_.Release();
}
inline void Task::set_allocated_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.id_.IsDefault()) {
          _impl_.id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MapReduce.Task.id)
}

// string state = 2;
inline void Task::clear_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.state_.ClearToEmpty();
}
inline const std::string& Task::state() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MapReduce.Task.state)
  return _internal_state();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task::set_state(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.state_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MapReduce.Task.state)
}
inline std::string* Task::mutable_state() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:MapReduce.Task.state)
  return _s;
}
inline const std::string& Task::_internal_state() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.state_.Get();
}
inline void Task::_internal_set_state(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.state_.Set(value, GetArena());
}
inline std::string* Task::_internal_mutable_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.state_.Mutable( GetArena());
}
inline std::string* Task::release_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:MapReduce.Task.state)
  return _impl_.state_.Release();
}
inline void Task::set_allocated_state(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.state_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.state_.IsDefault()) {
          _impl_.state_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MapReduce.Task.state)
}

// int32 index = 3;
inline void Task::clear_index() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.index_ = 0;
}
inline ::int32_t Task::index() const {
  // @@protoc_insertion_point(field_get:MapReduce.Task.index)
  return _internal_index();
}
inline void Task::set_index(::int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:MapReduce.Task.index)
}
inline ::int32_t Task::_internal_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.index_;
}
inline void Task::_internal_set_index(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.index_ = value;
}

// string file = 4;
inline void Task::clear_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.file_.ClearToEmpty();
}
inline const std::string& Task::file() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MapReduce.Task.file)
  return _internal_file();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task::set_file(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.file_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MapReduce.Task.file)
}
inline std::string* Task::mutable_file() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:MapReduce.Task.file)
  return _s;
}
inline const std::string& Task::_internal_file() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.file_.Get();
}
inline void Task::_internal_set_file(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.file_.Set(value, GetArena());
}
inline std::string* Task::_internal_mutable_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.file_.Mutable( GetArena());
}
inline std::string* Task::release_file() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:MapReduce.Task.file)
  return _impl_.file_.Release();
}
inline void Task::set_allocated_file(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.file_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.file_.IsDefault()) {
          _impl_.file_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MapReduce.Task.file)
}

// string workerId = 5;
inline void Task::clear_workerid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.workerid_.ClearToEmpty();
}
inline const std::string& Task::workerid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MapReduce.Task.workerId)
  return _internal_workerid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task::set_workerid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.workerid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MapReduce.Task.workerId)
}
inline std::string* Task::mutable_workerid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_workerid();
  // @@protoc_insertion_point(field_mutable:MapReduce.Task.workerId)
  return _s;
}
inline const std::string& Task::_internal_workerid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.workerid_.Get();
}
inline void Task::_internal_set_workerid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.workerid_.Set(value, GetArena());
}
inline std::string* Task::_internal_mutable_workerid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.workerid_.Mutable( GetArena());
}
inline std::string* Task::release_workerid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:MapReduce.Task.workerId)
  return _impl_.workerid_.Release();
}
inline void Task::set_allocated_workerid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.workerid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.workerid_.IsDefault()) {
          _impl_.workerid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MapReduce.Task.workerId)
}

// -------------------------------------------------------------------

// AckAndQueryNewTaskRequest

// int32 previousTaskIndex = 1;
inline void AckAndQueryNewTaskRequest::clear_previoustaskindex() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.previoustaskindex_ = 0;
}
inline ::int32_t AckAndQueryNewTaskRequest::previoustaskindex() const {
  // @@protoc_insertion_point(field_get:MapReduce.AckAndQueryNewTaskRequest.previousTaskIndex)
  return _internal_previoustaskindex();
}
inline void AckAndQueryNewTaskRequest::set_previoustaskindex(::int32_t value) {
  _internal_set_previoustaskindex(value);
  // @@protoc_insertion_point(field_set:MapReduce.AckAndQueryNewTaskRequest.previousTaskIndex)
}
inline ::int32_t AckAndQueryNewTaskRequest::_internal_previoustaskindex() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.previoustaskindex_;
}
inline void AckAndQueryNewTaskRequest::_internal_set_previoustaskindex(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.previoustaskindex_ = value;
}

// string state = 2;
inline void AckAndQueryNewTaskRequest::clear_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.state_.ClearToEmpty();
}
inline const std::string& AckAndQueryNewTaskRequest::state() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MapReduce.AckAndQueryNewTaskRequest.state)
  return _internal_state();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AckAndQueryNewTaskRequest::set_state(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.state_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MapReduce.AckAndQueryNewTaskRequest.state)
}
inline std::string* AckAndQueryNewTaskRequest::mutable_state() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_state();
  // @@protoc_insertion_point(field_mutable:MapReduce.AckAndQueryNewTaskRequest.state)
  return _s;
}
inline const std::string& AckAndQueryNewTaskRequest::_internal_state() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.state_.Get();
}
inline void AckAndQueryNewTaskRequest::_internal_set_state(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.state_.Set(value, GetArena());
}
inline std::string* AckAndQueryNewTaskRequest::_internal_mutable_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.state_.Mutable( GetArena());
}
inline std::string* AckAndQueryNewTaskRequest::release_state() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:MapReduce.AckAndQueryNewTaskRequest.state)
  return _impl_.state_.Release();
}
inline void AckAndQueryNewTaskRequest::set_allocated_state(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.state_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.state_.IsDefault()) {
          _impl_.state_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MapReduce.AckAndQueryNewTaskRequest.state)
}

// string workerId = 3;
inline void AckAndQueryNewTaskRequest::clear_workerid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.workerid_.ClearToEmpty();
}
inline const std::string& AckAndQueryNewTaskRequest::workerid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MapReduce.AckAndQueryNewTaskRequest.workerId)
  return _internal_workerid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AckAndQueryNewTaskRequest::set_workerid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.workerid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MapReduce.AckAndQueryNewTaskRequest.workerId)
}
inline std::string* AckAndQueryNewTaskRequest::mutable_workerid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_workerid();
  // @@protoc_insertion_point(field_mutable:MapReduce.AckAndQueryNewTaskRequest.workerId)
  return _s;
}
inline const std::string& AckAndQueryNewTaskRequest::_internal_workerid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.workerid_.Get();
}
inline void AckAndQueryNewTaskRequest::_internal_set_workerid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.workerid_.Set(value, GetArena());
}
inline std::string* AckAndQueryNewTaskRequest::_internal_mutable_workerid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.workerid_.Mutable( GetArena());
}
inline std::string* AckAndQueryNewTaskRequest::release_workerid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:MapReduce.AckAndQueryNewTaskRequest.workerId)
  return _impl_.workerid_.Release();
}
inline void AckAndQueryNewTaskRequest::set_allocated_workerid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.workerid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.workerid_.IsDefault()) {
          _impl_.workerid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MapReduce.AckAndQueryNewTaskRequest.workerId)
}

// -------------------------------------------------------------------

// AckAndQueryNewTaskResponse

// .MapReduce.Task task = 1;
inline bool AckAndQueryNewTaskResponse::has_task() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.task_ != nullptr);
  return value;
}
inline void AckAndQueryNewTaskResponse::clear_task() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.task_ != nullptr) _impl_.task_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::MapReduce::Task& AckAndQueryNewTaskResponse::_internal_task() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::MapReduce::Task* p = _impl_.task_;
  return p != nullptr ? *p : reinterpret_cast<const ::MapReduce::Task&>(::MapReduce::_Task_default_instance_);
}
inline const ::MapReduce::Task& AckAndQueryNewTaskResponse::task() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MapReduce.AckAndQueryNewTaskResponse.task)
  return _internal_task();
}
inline void AckAndQueryNewTaskResponse::unsafe_arena_set_allocated_task(::MapReduce::Task* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.task_);
  }
  _impl_.task_ = reinterpret_cast<::MapReduce::Task*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MapReduce.AckAndQueryNewTaskResponse.task)
}
inline ::MapReduce::Task* AckAndQueryNewTaskResponse::release_task() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MapReduce::Task* released = _impl_.task_;
  _impl_.task_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::MapReduce::Task* AckAndQueryNewTaskResponse::unsafe_arena_release_task() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:MapReduce.AckAndQueryNewTaskResponse.task)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::MapReduce::Task* temp = _impl_.task_;
  _impl_.task_ = nullptr;
  return temp;
}
inline ::MapReduce::Task* AckAndQueryNewTaskResponse::_internal_mutable_task() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.task_ == nullptr) {
    auto* p = CreateMaybeMessage<::MapReduce::Task>(GetArena());
    _impl_.task_ = reinterpret_cast<::MapReduce::Task*>(p);
  }
  return _impl_.task_;
}
inline ::MapReduce::Task* AckAndQueryNewTaskResponse::mutable_task() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::MapReduce::Task* _msg = _internal_mutable_task();
  // @@protoc_insertion_point(field_mutable:MapReduce.AckAndQueryNewTaskResponse.task)
  return _msg;
}
inline void AckAndQueryNewTaskResponse::set_allocated_task(::MapReduce::Task* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::MapReduce::Task*>(_impl_.task_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::MapReduce::Task*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.task_ = reinterpret_cast<::MapReduce::Task*>(value);
  // @@protoc_insertion_point(field_set_allocated:MapReduce.AckAndQueryNewTaskResponse.task)
}

// int32 mapWorkerCnt = 2;
inline void AckAndQueryNewTaskResponse::clear_mapworkercnt() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.mapworkercnt_ = 0;
}
inline ::int32_t AckAndQueryNewTaskResponse::mapworkercnt() const {
  // @@protoc_insertion_point(field_get:MapReduce.AckAndQueryNewTaskResponse.mapWorkerCnt)
  return _internal_mapworkercnt();
}
inline void AckAndQueryNewTaskResponse::set_mapworkercnt(::int32_t value) {
  _internal_set_mapworkercnt(value);
  // @@protoc_insertion_point(field_set:MapReduce.AckAndQueryNewTaskResponse.mapWorkerCnt)
}
inline ::int32_t AckAndQueryNewTaskResponse::_internal_mapworkercnt() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.mapworkercnt_;
}
inline void AckAndQueryNewTaskResponse::_internal_set_mapworkercnt(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.mapworkercnt_ = value;
}

// int32 reduceWorkerCnt = 3;
inline void AckAndQueryNewTaskResponse::clear_reduceworkercnt() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.reduceworkercnt_ = 0;
}
inline ::int32_t AckAndQueryNewTaskResponse::reduceworkercnt() const {
  // @@protoc_insertion_point(field_get:MapReduce.AckAndQueryNewTaskResponse.reduceWorkerCnt)
  return _internal_reduceworkercnt();
}
inline void AckAndQueryNewTaskResponse::set_reduceworkercnt(::int32_t value) {
  _internal_set_reduceworkercnt(value);
  // @@protoc_insertion_point(field_set:MapReduce.AckAndQueryNewTaskResponse.reduceWorkerCnt)
}
inline ::int32_t AckAndQueryNewTaskResponse::_internal_reduceworkercnt() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.reduceworkercnt_;
}
inline void AckAndQueryNewTaskResponse::_internal_set_reduceworkercnt(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.reduceworkercnt_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace MapReduce


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_MapReduce_2eproto_2epb_2eh
