// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: MapReduce.proto

#include "MapReduce.pb.h"
#include "MapReduce.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace MapReduce {

static const char* TaskService_method_names[] = {
  "/MapReduce.TaskService/AckAndQueryNewTask",
};

std::unique_ptr< TaskService::Stub> TaskService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TaskService::Stub> stub(new TaskService::Stub(channel, options));
  return stub;
}

TaskService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AckAndQueryNewTask_(TaskService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TaskService::Stub::AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::MapReduce::AckAndQueryNewTaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AckAndQueryNewTask_, context, request, response);
}

void TaskService::Stub::async::AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AckAndQueryNewTask_, context, request, response, std::move(f));
}

void TaskService::Stub::async::AckAndQueryNewTask(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AckAndQueryNewTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>* TaskService::Stub::PrepareAsyncAckAndQueryNewTaskRaw(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::MapReduce::AckAndQueryNewTaskResponse, ::MapReduce::AckAndQueryNewTaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AckAndQueryNewTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::MapReduce::AckAndQueryNewTaskResponse>* TaskService::Stub::AsyncAckAndQueryNewTaskRaw(::grpc::ClientContext* context, const ::MapReduce::AckAndQueryNewTaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAckAndQueryNewTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

TaskService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TaskService::Service, ::MapReduce::AckAndQueryNewTaskRequest, ::MapReduce::AckAndQueryNewTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TaskService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::MapReduce::AckAndQueryNewTaskRequest* req,
             ::MapReduce::AckAndQueryNewTaskResponse* resp) {
               return service->AckAndQueryNewTask(ctx, req, resp);
             }, this)));
}

TaskService::Service::~Service() {
}

::grpc::Status TaskService::Service::AckAndQueryNewTask(::grpc::ServerContext* context, const ::MapReduce::AckAndQueryNewTaskRequest* request, ::MapReduce::AckAndQueryNewTaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace MapReduce

